FROM node:alpine
RUN apk add --no-cache git bash wget

ENV APP_DIR=/usr/src/app
WORKDIR $APP_DIR
COPY app/ .

# Install UI5 tooling
RUN npm config set @sap:registry "https://npm.sap.com" -g
RUN npm install --global @ui5/cli

# Exposing port 8080
EXPOSE 8080

# docker-entrypoint
COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
RUN apk del git

ENTRYPOINT ["/docker-entrypoint.sh"]